# sklearn学习笔记
- 代码实战

## 统计信息
- 两大类：定性分析和定量分析
- 最大、最小、均值、标准差、方差、极差、中位数
---
其他


In [4]:
import numpy as np
import sklearn as sk
data = np.random.normal(1,5,10) # 正态分布
data = np.random.randint(1,5,10) # 均匀分布
print(repr(data))
data = [1,5,8,2,4,1]
print(data)
# 各种统计指标
print('均值：%s,最小值:%s,最大值:%s,方差:%s,标准差:%s,中位数:%s,极差:%s'%(np.mean(data),np.min(data),np.max(data),np.var(data),np.std(data),np.median(data),np.ptp(data)))
print(np.cov(data),np.corrcoef(data)) # 协方差，相关系数

array([3, 2, 3, 4, 4, 1, 2, 4, 4, 3])
[1, 5, 8, 2, 4, 1]
均值：3.5,最小值:1,最大值:8,方差:6.25,标准差:2.5,中位数:3.0,极差:7
7.5 1.0


## 加载数据集
- 使用默认的iris数据集
- 注意：内置数据集以bunch类型存在，包含data、target等成员

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()#导入IRIS数据集,sklearn.utils.Bunch类型
#data = sk.datasets.load_iris()
iris.data#特征矩阵
iris.target#目标向量

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 数据预处理
- 消除量纲：针对列（特征），将各个特征调整为标准正态分布，具体方法：Z标准化、极差标准化
- 规范化：针对行（样本），将每个样本的长度限定为单位向量
- 连续特征离散化：二值化
- 离散特征数值化：one-hot编码（哑编码）

In [77]:
#预处理
#dir(sk.preprocessing)
new_data = sk.preprocessing.StandardScaler().fit_transform(iris.data)
#除了Z标准化StandardScaler，还有其他标准化方法：MinMaxScaler极差标准化、规范化Normalizer
#注：Z标准化只对列做处理（去量纲影响），而规范化将行处理为单位向量
bin_data = sk.preprocessing.Binarizer(threshold=3).fit_transform(iris.data) # 二值化，阈值为3
one_data = sk.preprocessing.OneHotEncoder().fit_transform(iris.target.reshape((-1,1))) # 独热编码
print(new_data[:5])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


In [75]:
data = np.array([[1,'a',10],[2,'b',-10],[4,'D',20],[2,'Z',30]])
data_y = np.array([i[0] for i in data])
#one-hot编码，输入必须是array类型，而且是列向量(正整数),按照取值升序排列，输出三元组形式表示的对角矩阵
one_data = sk.preprocessing.OneHotEncoder().fit_transform(data_y.reshape(-1,1))
#print(one_data)
test = np.array([2,7,1]).reshape(-1,1)
out = sk.preprocessing.OneHotEncoder().fit_transform(test.reshape(-1,1))
#out = sk.preprocessing.OneHotEncoder().fit_transform(iris.target.reshape(-1,1))
print(out)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0


In [86]:
data = np.array([[1,-200,10],[2,-230,-10],[4,-300,20],[2,-157,30]])
# 默认用均值自动填充缺失值
sk.preprocessing.Imputer().fit_transform(np.vstack((np.array([np.nan,-230,np.nan]),data)))

array([[   2.25, -230.  ,   12.5 ],
       [   1.  , -200.  ,   10.  ],
       [   2.  , -230.  ,  -10.  ],
       [   4.  , -300.  ,   20.  ],
       [   2.  , -157.  ,   30.  ]])

## 数据变换
- 多项式、对数、指数
- 也可以自定义函数

In [89]:
from sklearn.preprocessing import PolynomialFeatures
#多项式转换,参数degree为度，默认值为2
PolynomialFeatures().fit_transform(iris.data)
print(np.log1p(10))
# 也可以自定义
from numpy import log1p # log(1+x)
from sklearn.preprocessing import FunctionTransformer
#自定义转换函数为对数函数的数据变换
#第一个参数是单变元函数
FunctionTransformer(log1p).fit_transform(iris.data)

2.3978952728


## 特征选择
从发散性和相关性两个维度来筛选特征，主要方法：
- filter：过滤法
- wrapper：包装法
- embedded：嵌入法

In [90]:
from sklearn.feature_selection import VarianceThreshold
#方差选择法，返回值为特征选择后的数据,参数threshold为方差的阈值
VarianceThreshold(threshold=3).fit_transform(iris.data)

array([[ 1.4],
       [ 1.4],
       [ 1.3],
       [ 1.5],
       [ 1.4],
       [ 1.7],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.5],
       [ 1.6],
       [ 1.4],
       [ 1.1],
       [ 1.2],
       [ 1.5],
       [ 1.3],
       [ 1.4],
       [ 1.7],
       [ 1.5],
       [ 1.7],
       [ 1.5],
       [ 1. ],
       [ 1.7],
       [ 1.9],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.4],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.2],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.3],
       [ 1.3],
       [ 1.6],
       [ 1.9],
       [ 1.4],
       [ 1.6],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 4.7],
       [ 4.5],
       [ 4.9],
       [ 4. ],
       [ 4.6],
       [ 4.5],
       [ 4.7],
       [ 3.3],
       [ 4.6],
       [ 3.9],
       [ 3.5],
       [ 4.2],
       [ 4. ],
       [ 4.7],
       [ 3.6],
       [ 4.4],
       [ 4

In [2]:
%%time
import tensorflow as tf
import time
tf.constant()
time.sleep(3)
tf.constant
print('hello')

TypeError: constant() missing 1 required positional argument: 'value'

In [1]:
#https://gist.github.com/dandelionmane/4f02ab8f1451e276fea1f165a20336f1#file-slides-pdf
import os
import tensorflow as tf
import urllib

LOGDIR = '/tmp/mnist_tutorial/'
GIST_URL = 'https://gist.githubusercontent.com/dandelionmane/4f02ab8f1451e276fea1f165a20336f1/raw/dfb8ee95b010480d56a73f324aca480b3820c180'

### MNIST EMBEDDINGS ###
mnist = tf.contrib.learn.datasets.mnist.read_data_sets(train_dir=LOGDIR + 'data', one_hot=True)
### Get a sprite and labels file for the embedding projector ###
urllib.urlretrieve(GIST_URL + 'labels_1024.tsv', LOGDIR + 'labels_1024.tsv')
urllib.urlretrieve(GIST_URL + 'sprite_1024.png', LOGDIR + 'sprite_1024.png')


def conv_layer(input, size_in, size_out, name="conv"):
  with tf.name_scope(name):
    w = tf.Variable(tf.truncated_normal([5, 5, size_in, size_out], stddev=0.1), name="W")
    b = tf.Variable(tf.constant(0.1, shape=[size_out]), name="B")
    conv = tf.nn.conv2d(input, w, strides=[1, 1, 1, 1], padding="SAME")
    act = tf.nn.relu(conv + b)
    tf.summary.histogram("weights", w)
    tf.summary.histogram("biases", b)
    tf.summary.histogram("activations", act)
    return tf.nn.max_pool(act, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


def fc_layer(input, size_in, size_out, name="fc"):
  with tf.name_scope(name):
    w = tf.Variable(tf.truncated_normal([size_in, size_out], stddev=0.1), name="W")
    b = tf.Variable(tf.constant(0.1, shape=[size_out]), name="B")
    act = tf.nn.relu(tf.matmul(input, w) + b)
    tf.summary.histogram("weights", w)
    tf.summary.histogram("biases", b)
    tf.summary.histogram("activations", act)
    return act


def mnist_model(learning_rate, use_two_conv, use_two_fc, hparam):
  tf.reset_default_graph()
  sess = tf.Session()

  # Setup placeholders, and reshape the data
  x = tf.placeholder(tf.float32, shape=[None, 784], name="x")
  x_image = tf.reshape(x, [-1, 28, 28, 1])
  tf.summary.image('input', x_image, 3)
  y = tf.placeholder(tf.float32, shape=[None, 10], name="labels")

  if use_two_conv:
    conv1 = conv_layer(x_image, 1, 32, "conv1")
    conv_out = conv_layer(conv1, 32, 64, "conv2")
  else:
    conv1 = conv_layer(x_image, 1, 64, "conv")
    conv_out = tf.nn.max_pool(conv1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")

  flattened = tf.reshape(conv_out, [-1, 7 * 7 * 64])

  if use_two_fc:
    fc1 = fc_layer(flattened, 7 * 7 * 64, 1024, "fc1")
    embedding_input = fc1
    embedding_size = 1024
    logits = fc_layer(fc1, 1024, 10, "fc2")
  else:
    embedding_input = flattened
    embedding_size = 7*7*64
    logits = fc_layer(flattened, 7*7*64, 10, "fc")

  with tf.name_scope("xent"):
    xent = tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(
            logits=logits, labels=y), name="xent")
    tf.summary.scalar("xent", xent)

  with tf.name_scope("train"):
    train_step = tf.train.AdamOptimizer(learning_rate).minimize(xent)

  with tf.name_scope("accuracy"):
    correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    tf.summary.scalar("accuracy", accuracy)

  summ = tf.summary.merge_all()


  embedding = tf.Variable(tf.zeros([1024, embedding_size]), name="test_embedding")
  assignment = embedding.assign(embedding_input)
  saver = tf.train.Saver()

  sess.run(tf.global_variables_initializer())
  writer = tf.summary.FileWriter(LOGDIR + hparam)
  writer.add_graph(sess.graph)

  config = tf.contrib.tensorboard.plugins.projector.ProjectorConfig()
  embedding_config = config.embeddings.add()
  embedding_config.tensor_name = embedding.name
  embedding_config.sprite.image_path = LOGDIR + 'sprite_1024.png'
  embedding_config.metadata_path = LOGDIR + 'labels_1024.tsv'
  # Specify the width and height of a single thumbnail.
  embedding_config.sprite.single_image_dim.extend([28, 28])
  tf.contrib.tensorboard.plugins.projector.visualize_embeddings(writer, config)

  for i in range(2001):
    batch = mnist.train.next_batch(100)
    if i % 5 == 0:
      [train_accuracy, s] = sess.run([accuracy, summ], feed_dict={x: batch[0], y: batch[1]})
      writer.add_summary(s, i)
    if i % 500 == 0:
      sess.run(assignment, feed_dict={x: mnist.test.images[:1024], y: mnist.test.labels[:1024]})
      saver.save(sess, os.path.join(LOGDIR, "model.ckpt"), i)
    sess.run(train_step, feed_dict={x: batch[0], y: batch[1]})

def make_hparam_string(learning_rate, use_two_fc, use_two_conv):
  conv_param = "conv=2" if use_two_conv else "conv=1"
  fc_param = "fc=2" if use_two_fc else "fc=1"
  return "lr_%.0E,%s,%s" % (learning_rate, conv_param, fc_param)

def main():
  # You can try adding some more learning rates
  for learning_rate in [1E-4]:

    # Include "False" as a value to try different model architectures
    for use_two_fc in [True]:
      for use_two_conv in [True]:
        # Construct a hyperparameter string for each one (example: "lr_1E-3,fc=2,conv=2)
        hparam = make_hparam_string(learning_rate, use_two_fc, use_two_conv)
        print('Starting run for %s' % hparam)

        # Actually run with the new settings
        mnist_model(learning_rate, use_two_fc, use_two_conv, hparam)


if __name__ == '__main__':
  main()

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/mnist_tutorial/data\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/mnist_tutorial/data\train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/mnist_tutorial/data\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/mnist_tutorial/data\t10k-labels-idx1-ubyte.gz


AttributeError: module 'urllib' has no attribute 'urlretrieve'